---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  image:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        version:
          - '1.12.19'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          submodules: true
      - uses: 'actions/cache@v3'
        with:
          path: 'cache/uxgpro-${{ matrix.version }}'
          key: 'uxgpro-${{ matrix.version }}'
      - run: 'make FIRMWARE_VERSION=${{ matrix.version }}'
